### ISSUE TITLE
[FEATURE] Enhance alerting stats API

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/alerting#836] opened 2023-03-23 23:51 UTC
**Is your feature request related to a problem?**
The monitor stats api doesn't give a simple overview on how the Alerting plugin is running. How many monitors are currently running and what monitor types are they? When were the last generated alerts? How long are the monitor executing for?
**What solution would you like?**
I would like a good summarized view of metrics of the Alerting plugin and how the monitors are running and having a detailed breakdown on this info.

**Comment by engechas** [comment] 2024-04-12 19:51
Closing as a duplicate of #877

**Closed by engechas** 2024-04-12 19:51 UTC
Labels: enhancement
