### ISSUE TITLE
[BUG] swallowed mustache error

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#53] opened 2021-06-02 21:41 UTC
<a href="https://github.com/tjbaker"><img src="https://avatars.githubusercontent.com/u/3188587?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tjbaker](https://github.com/tjbaker)**
_Thursday Jan 30, 2020 at 20:15 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/160_

----

Using the following mustache template for alerting trigger messages:

```
Monitor "{{ctx.monitor.name}}" just entered alert state. Please investigate the issue!

- Trigger: {{ctx.trigger.name}}
- Severity: {{ctx.trigger.severity}}
- Period start: {{ctx.periodStart}}
- Period end: {{ctx.periodEnd}}
- Total Results: {{ctx.results.0.hits.total.value}}

First Result From Alert (1 of {{ctx.results.0.hits.total.value}} events):
{{#ctx.results.0.hits.hits.0}}
  Level : {{_source.level}}
  Logger: {{_source.logger}}
  Message: {{_source.message}}
{{/ctx.results.0.hits.hits.0}}
```

This code works well when the trigger fires and there are hits.
When I try to use the above and send a test message via the Kibana UI and there are no hits nothing happens, no messages are sent and there is no visible changes in the Kibana UI.  I see the following exception via developer tools:

```
action_results: {,…}
rgOS928B9DSJTFBIUlr3: {id: "rgOS928B9DSJTFBIUlr3", name: "sns", output: {}, throttled: false, executionTime: 1580414142870,…}
id: "rgOS928B9DSJTFBIUlr3"
name: "sns"
output: {}
throttled: false
executionTime: 1580414142870
error: "Error running com.github.mustachejava.codes.DefaultMustache@3236b9d7"
```

You can reference non-existing elements in the template and they're omitted from the output, but it seems that the template engine is not forgiving of missing "sections".  If you remove the {{#ctx.results.0.hits.hits.0}} block the test message with zero docs will succeed.

**Comment by aditjind** [comment] 2021-06-27 22:48
Hi @tjbaker 

This is inherently by design for the Mustache templates where if the arrays which you are iterating over have zero elements, mustache wont be able to iterate over it and throw the `com.github.mustachejava.MustacheException`, as seen in this case. 

I suggest you adding an empty check before iterating over the array to see if the array is having elements. 

```
{{^ctx.results.0.hits.hits.length}}
  Level : {{_source.level}}
  Logger: {{_source.logger}}
  Message: {{_source.message}}
{{/ctx.results.0.hits.hits.length}}
```

{{^`name`.length}} is the variable which will help you check the length of the array and then iterate over it. 

Please check these references for better understanding: [Reference_1](https://stackoverflow.com/questions/11653764/mustache-how-to-detect-array-is-not-empty) [Reference_2](https://stackoverflow.com/questions/8745802/dealing-with-an-empty-list-in-mustache-js)

**Comment by partlov** [comment] 2022-11-18 13:07
I thing that we should maybe close this issue, as it is something which works by design and there is easy work around.

**Comment by brijos** [comment] 2023-04-04 22:27
Thanks @partlov. Closing.

**Closed by brijos** 2023-04-04 22:27 UTC
Labels: bug

**Comment by d9-Mark** [comment] 2024-06-18 19:14
Hi, looping back here because I'm still running into issues executing Mustache code. I am confident the length of what I need to iterate over is not 0.

Sending this as plaintext because another headache I'm dealing with, regardless, this returns me an empty array, even in preview.

"results": [
  {{^ctx.results.0.aggregations.login_count.buckets}}
  {
    "user": "{{key}}",
    "doc_count": "{{doc_count}}",
    "success_count": "{{successful_logins.count.value}}",
    "city": "{{geo_city.buckets.0.key}}",
    "country": "{{geo_country.buckets.0.key}}"
  }
  {{/ctx.results.0.aggregations.login_count.buckets}}
]

When changing this to 
"results": [
  {{#ctx.results.0.aggregations.login_count.buckets}}
  {
    "user": "{{key}}",
    "doc_count": "{{doc_count}}",
    "success_count": "{{successful_logins.count.value}}",
    "city": "{{geo_city.buckets.0.key}}",
    "country": "{{geo_country.buckets.0.key}}"
  }
  {{/ctx.results.0.aggregations.login_count.buckets}}
]

I get the generic mustache error, but in the preview I can clearly see an array of results populating. Any ideas on a solution for this? 

Thanks.
