### ISSUE TITLE
[BUG] Duplicate Alerts created after restarting OpenDistro while a single Alert is in Active state

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#93] opened 2021-06-02 21:50 UTC
<a href="https://github.com/amar-mhatre"><img src="https://avatars.githubusercontent.com/u/79559035?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [amar-mhatre](https://github.com/amar-mhatre)**
_Wednesday Feb 24, 2021 at 04:41 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/356_

----

**Describe the bug**
A Monitor has raised an alert and it is active, if one restarts open-distro, multiple alerts are raised by trigger for same query and keeps generating.

**To Reproduce**
1. Create monitor trigger and action
2. Once an alert is generated and it is active state restart open-distro service
3.  After restarting one can see same monitor and trigger start generating multiple alerts every time monitor executes as per schedule all alerts are active and can be acknowledge separately.

**Expected behavior**
Even after restarting open-distro should maintain the state of an alerts, like it is maintaining before restarting

**Desktop (please complete the following information):**
 - OS: Debain
 - Version [Opendistro 6.7.1]

**Comment by toepkerd** [comment] 2022-07-11 22:43
Unable to reproduce the issue. Possibly due to later iterations of OpenSearch already fixing it passively.

**Comment by qreshi** [comment] 2022-07-11 22:55
Closing issue. Feel free to re-open if this issue is seen again.

**Closed by qreshi** 2022-07-11 22:55 UTC
Labels: bug
