### ISSUE TITLE
Support SQL for alerting

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#90] opened 2021-06-02 21:50 UTC
<a href="https://github.com/y3n11"><img src="https://avatars.githubusercontent.com/u/17970924?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [y3n11](https://github.com/y3n11)**
_Wednesday Jan 27, 2021 at 23:39 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/341_

----

It will be preferable to create monitors using SQL queries

**Comment by qreshi** [comment] 2022-02-18 16:33
Closing this issue as it's a duplicate of https://github.com/opensearch-project/alerting/issues/27

**Closed by qreshi** 2022-02-18 16:33 UTC
Labels: enhancement, backlog
