### ISSUE TITLE
[FEATURE] Separate the Monitors and Destinations according to Tenant or by given specific group.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/alerting#459] opened 2022-05-23 14:59 UTC
**Is your feature request related to a problem?**
Coming from Issue: https://github.com/opensearch-project/helm-charts/issues/266 
The main problem statement is the [limit access by backend role](https://opensearch.org/docs/latest/monitoring-plugins/alerting/security/#advanced-limit-access-by-backend-role ) allows other users to access monitors who share at least one backend role. With this it's not able to restrict a specific users group backed by LDAP and grants other users access to who is part of more than one backend role.

**What solution would you like?**

- Separate the Monitoring and Destinations according to Tenant or Separate the Monitoring and Destinations according to role, where a role is mapped to a group which does not check shared user groups.
- Disable access to shared user groups when enabled `allow_shared_roles: false`.

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
For more testing details please refer to issue https://github.com/opensearch-project/helm-charts/issues/266

**Comment by sevenval-admins** [comment] 2022-06-02 08:02
Hi everybody, is there any news here?

**Comment by lezzago** [comment] 2022-06-03 17:24
@sevenval-admins and @prudhvigodithi, we are currently looking into enhancing the limit by backend role support by allowing users to specify which backend roles will be associated to a monitor. Will this enhancement fix the problem mentioned in this issue? We also have an issue tracking this in #138.

**Comment by sevenval-admins** [comment] 2022-06-07 07:57
Hi @lezzago thank you for your reply and the support. I think that the enhancement will solve the problem. By the way the same should be done for the Notifications-Plugin too.

**Comment by rishabhmaurya** [comment] 2022-06-09 18:04
duplicate of https://github.com/opensearch-project/alerting/issues/138.

**Closed by rishabhmaurya** 2022-06-09 18:04 UTC
Labels: enhancement, untriaged
