### ISSUE TITLE
[BUG] Could not find 1.2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by mann2108** [opensearch-project/alerting#250] opened 2021-12-06 06:51 UTC
**Describe the bug**
Could not find 1.2.0.0-SNAPSHOT

**Other plugins installed**
None

**To Reproduce**
Till yesterday everything is working fine, but today while running ./gradlew run I got this error.
![image](https://user-images.githubusercontent.com/44433995/144800676-211becd3-28b0-44f1-98fd-6313f400306c.png)

**Expected behavior**
It should work without any errors

**Desktop (please complete the following information):**
 - Running on VM - Centos

Temporary I have to change the build.gradle with 1.3.0.0-SNAPSHOT and it's working. 
![image](https://user-images.githubusercontent.com/44433995/144806592-861269a7-c793-4464-8cf8-56fb20a38da1.png)

**Comment by dblock** [comment] 2021-12-07 16:43
This was caused by https://github.com/opensearch-project/opensearch-build/issues/1261. This should be fixed now, but we haven't resolved the root cause. Can you please confirm and close?

**Comment by mann2108** [comment] 2021-12-07 16:58
@dblock Verified it seems working now, Thanks 👍🏼

**Closed** 2021-12-07 16:58 UTC
Labels: bug, Beta, untriaged
