### ISSUE TITLE
[2.0.0][Distribution][BUG] Failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/alerting#351] opened 2022-03-14 19:11 UTC
```
2022-03-14 18:54:21 INFO     Sanity testing alerting
2022-03-14 18:54:21 INFO     Executing "git init" in /tmp/tmplk9kqyh6/alerting
2022-03-14 18:54:21 INFO     Executing "git remote add origin https://github.com/opensearch-project/alerting.git" in /tmp/tmplk9kqyh6/alerting
2022-03-14 18:54:21 INFO     Executing "git fetch --depth 1 origin main" in /tmp/tmplk9kqyh6/alerting
2022-03-14 18:54:21 INFO     Executing "git checkout FETCH_HEAD" in /tmp/tmplk9kqyh6/alerting
2022-03-14 18:54:21 INFO     Executing "git rev-parse HEAD" in /tmp/tmplk9kqyh6/alerting
2022-03-14 18:54:21 INFO     Checked out https://github.com/opensearch-project/alerting.git@main into /tmp/tmplk9kqyh6/alerting at 9487c00a388dbc3d9a5bce602a2b70b0ec20f90f
2022-03-14 18:54:21 INFO     Executing "./gradlew properties -Dopensearch.version=2.0.0-SNAPSHOT -Dbuild.snapshot=true" in /tmp/tmplk9kqyh6/alerting

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/tmplk9kqyh6/alerting/alerting/build.gradle' line: 13

* What went wrong:
A problem occurred evaluating project ':alerting'.
> Failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.
   > Could not create plugin of type 'GlobalBuildInfoPlugin'.
      > Could not generate a decorated class for type GlobalBuildInfoPlugin.
         > org/gradle/internal/jvm/inspection/JvmInstallationMetadata

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 27s
2022-03-14 18:54:52 ERROR    CI Manifest check failed
Traceback (most recent call last):
  File "./src/run_ci.py", line 25, in <module>
    sys.exit(main())
  File "./src/run_ci.py", line 21, in main
    CiManifests.from_file(args.manifest, args).check()
  File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_manifest.py", line 21, in check
    self.__check__()
  File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_input_manifest.py", line 36, in __check__
    ci_check_list.check()
  File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_check_list_source.py", line 43, in check
    instance = klass(self.component, self.git_repo, self.target, check.args)
  File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_check_gradle_properties.py", line 19, in __init__
    self.properties = self.__get_properties()
  File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_check_gradle_properties.py", line 30, in __get_properties
    return PropertiesFile(self.git_repo.output(cmd))
  File "/home/runner/work/opensearch-build/opensearch-build/src/git/git_repository.py", line 78, in output
    return subprocess.check_output(command, cwd=cwd, shell=True).decode().strip()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command './gradlew properties -Dopensearch.version=2.0.0-SNAPSHOT -Dbuild.snapshot=true' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

**Comment by lezzago** [comment] 2022-03-28 21:44
@peterzhuamazon can you let me know if the issue is now resolved?

**Comment by peterzhuamazon** [comment] 2022-03-28 23:01
> @peterzhuamazon can you let me know if the issue is now resolved?

Is alerting ready to be added to 2.0.0?
The previous PR is closed already.

**Comment by lezzago** [comment] 2022-03-28 23:52
Yes we have updated Alerting to 2.0 with this [PR](https://github.com/opensearch-project/alerting/pull/357).

**Comment by lezzago** [comment] 2022-04-05 20:10
Closing as this is fixed now

**Closed by lezzago** 2022-04-05 20:10 UTC
Labels: v2.0.0, release
