### ISSUE TITLE
[BUG] Slack alerting notifications regression

### ISSUE THREAD

**Issue by sas1024** [opensearch-project/alerting#529] opened 2022-08-24 13:49 UTC
**What is the bug?**
In OpenSearch 1.2.x all Slack notifications was formatted as `$subject \n\n $message`. And all worked very fine.
In OpenSearch 2.2.0 all Slack notifications formatted as `Alerting-Notification Action \n\n $subject \n\n $message`. And for now all slack notifications with alerts bad readable because of prefix "Alerting-Notification Action".

**How can one reproduce the bug?**
Just create any alert with slack notification.

**What is the expected behavior?**
Please, return old formatting for slack notifications. `$subject \n\n $message`, without hardcoded prefix "Alerting-Notification Action".

**Do you have any additional context?**
As i see, hardcoded prefix used [here](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/NotificationApiUtils.kt#L144).

**Comment by praveensameneni** [comment] 2022-09-12 04:10
Thank you for finding the issue, looking into it.

**Comment by uroskarama** [comment] 2022-11-16 22:39
@praveensameneni I have created a pull request with a "hacky" solution to this issue by passing a blank space, since from my investigation the notification plugin does't send a notification if null or empty string to be passed (see [here](https://github.com/opensearch-project/notifications/blob/main/notifications/core-spi/src/main/kotlin/org/opensearch/notifications/spi/model/MessageContent.kt#L25) )
I confirmed by manual testing that it works properly and sends slack messages without this "Alerting-Notification Action".
About integration tests, we don't have any in alerting testing content notifications from what I can see? It is possible to create a socket server to pass notifications to it and then assert them as part of integration test, would that be an acceptable solution?

**Comment by aviramaz** [comment] 2022-12-17 10:06
+1,
Seems like a wider issue.
@praveensameneni - This issue is also impacting SNS, when triggering to SNS, the email subject is no longer the correct one but the "Alerting-Notification Action" is being received, started after upgrading to 2.x from 1.x.
We can no longer distinguish between the alerts due to it by the Subject.

**Comment by lezzago** [comment] 2023-04-07 17:45
This issue has been fixed with the PR

**Closed by lezzago** 2023-04-07 17:45 UTC
Labels: bug
